### ISSUE TITLE
Long-running task triggered by slack message

### ISSUE THREAD

**Issue by richcorbs** [slack-ruby/slack-ruby-client#129]
Hello,

I am trying to create a bot that upon hearing a command triggers a long-running shell task that I'm running via backticks. After the long-running task completes I get the following before I can send the "success" message to the channel:

ERROR -- : Actor crashed!
Errno::EPIPE: Broken pipe

I'm not quite sure how to troubleshoot it or fix it. The long-running task completes successfully but the actor crashes immediately thereafter. Maybe this is the result of a slack disconnect/inactivity timeout?

Any thoughts are appreciated.

**Comment by dblock** [comment]
Is there an exception with a stack above the crash?

**Comment by richcorbs** [comment]
Below is the last line of regular output (`>>>>: lock file removed`) and the subsequent backtrace.

The long-running action is wrapped in a begin-rescue-end so it may have handled any exception. Line 338 (see bottom of backtrace) is the end of the bot file.

```
>>>>: lock file removed
E, [2017-01-24T15:09:22.203956 #25298] ERROR -- : Actor crashed!
Errno::EPIPE: Broken pipe
	/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:379:in `syswrite_nonblock'
	/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:379:in `write_nonblock'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:62:in `block in syswrite'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:390:in `synchronize'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:59:in `syswrite'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:356:in `do_write'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:250:in `write'
	/usr/local/rvm/gems/ruby-2.3.0/gems/slack-ruby-client-0.7.7/lib/slack/real_time/concurrency/celluloid.rb:63:in `write'
	/usr/local/rvm/gems/ruby-2.3.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi.rb:228:in `send_frame'
	/usr/local/rvm/gems/ruby-2.3.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi.rb:191:in `frame'
	/usr/local/rvm/gems/ruby-2.3.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi.rb:370:in `emit_frame'
	/usr/local/rvm/gems/ruby-2.3.0/gems/websocket-driver-0.6.4/lib/websocket/driver/hybi.rb:123:in `parse'
	/usr/local/rvm/gems/ruby-2.3.0/gems/websocket-driver-0.6.4/lib/websocket/driver/client.rb:63:in `parse'
	/usr/local/rvm/gems/ruby-2.3.0/gems/slack-ruby-client-0.7.7/lib/slack/real_time/concurrency/celluloid.rb:58:in `handle_read'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
/usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:35:in `terminate': task was terminated (Celluloid::TaskTerminated)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:323:in `block in cleanup'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `cleanup'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:307:in `shutdown'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:299:in `handle_crash'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:171:in `rescue in run'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:150:in `run'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
	from (celluloid):0:in `remote procedure call'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/slack-ruby-client-0.7.7/lib/slack/real_time/client.rb:51:in `start!'
	from ./bot.rb:338:in `<main>'
```

**Comment by dblock** [comment]
So this looks like the socket has been closed and sending any data over it is no longer possible, at least in response to something incoming.

As a workaround you can probably send things back via the web client interface:

```ruby
client.web_client.chat_postMessage channel: data.channel, text: "Hi"
```

Not sure if there's anything we can do here to fix the RTM scenario though.

**Comment by richcorbs** [comment]
Is there a better way for me to handle long-running commands?

**Comment by dblock** [comment]
How do you launch this long-running task?

Generally, Celluloid is not a true concurrency platform unless everything is non-blocking. So you should probably be using something like delayed job or resque to execute long running tasks that are synchronous. 

But again, I am not sure why in this case you're not able to send a message to slack. I would imagine that the RTM connection is open and available until slack decides otherwise or an actual network error occurs.

**Comment by richcorbs** [comment]
Here is how I'm calling the long-running command:

```
cmd = "cd /var/www/mydir/current && export BRANCH=master && cap production deploy"
output = `#{cmd}`
```

**Comment by richcorbs** [comment]
Would extending the websocket_ping during setup help in this case?

**Comment by dblock** [comment]
Think of Celluloid as a single thread that is evented, so it looks like it's asynchronous. So while it may seem like you're doing this operation asynchronously, you're actually blocking the main thread on which Celluloid runs, so everything stops. You can't do things like ping or process packets or maintain connections while you're doing something else. 

Move this into a delayed job and have the delayed job report back to Slack via the web API.
