### ISSUE TITLE
NoMethodError: undefined method `running?'

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-client#146]
```
NoMethodError: undefined method `running?' for #<Slack::RealTime::Concurrency::Celluloid::Socket:0x007ff96d87aa50>
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by dblock** [comment]
Removing the `running?` check causes

```
E, [2017-04-30T11:15:46.369906 #49810] ERROR -- : Actor crashed!
ThreadError: Target thread must not be current thread
	/Users/dblock/.rvm/gems/ruby-2.2.1/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:37:in `join'
	/Users/dblock/.rvm/gems/ruby-2.2.1/gems/celluloid-0.17.3/lib/celluloid/actor.rb:97:in `join'
	/Users/dblock/.rvm/gems/ruby-2.2.1/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:28:in `terminate'
	/Users/dblock/.rvm/gems/ruby-2.2.1/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:59:in `terminate'
	/Users/dblock/source/slack/slack-ruby-client/dblock/lib/slack/real_time/concurrency/celluloid.rb:41:in `ensure in run_loop'
```

**Comment by dblock** [comment]
Failing spec in https://github.com/dblock/slack-ruby-client/tree/issue-146.

**Comment by dblock** [comment]
Related https://github.com/slack-ruby/slack-ruby-client/pull/106, cc: @kandadaboggu
