### ISSUE TITLE
Resolv::ResolvError: DNS result has no information for cerberus-xxxx.lb.slack-msgs.com

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-client#218]
This causes the a bot to not start.

```
Resolv::ResolvError: DNS result has no information for cerberus-xxxx.lb.slack-msgs.com
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/tcp_socket.rb:102:in `create_socket'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/tcp_socket.rb:53:in `initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/socket.rb:39:in `new'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/socket.rb:39:in `new'
	/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.12.0/lib/slack/real_time/concurrency/celluloid.rb:98:in `build_socket'
	/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.12.0/lib/slack/real_time/concurrency/celluloid.rb:33:in `run_loop'
	/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.12.0/lib/slack/real_time/concurrency/celluloid.rb:28:in `connect!'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by dblock** [comment]
https://github.com/celluloid/celluloid-io/issues/188#issuecomment-414666403 suggests resolving the name with the ruby dns resolver first
