### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-client#365]
The `im_open` and `channels_list` methods no longer work since February 2021, purge them from the library.

**Comment by rgaufman** [comment]
Yes please! - Just trying this gem for the first time and first thing I try:

```
irb(main):015:0> client.channels_list.channels
W, [2021-02-28T12:09:37.036449 #60083]  WARN -- : channels.list: This method is deprecated. It will stop functioning in February 2021 and will not work with newly created apps after June 10th, 2020. Alternative methods: conversations.list, users.conversations.
Traceback (most recent call last):
       16: from (irb):14
       15: from (irb):15:in `rescue in irb_binding'
       14: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/slack-ruby-client-0.16.0/lib/slack/web/api/endpoints/channels.rb:180:in `channels_list'
       13: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/slack-ruby-client-0.16.0/lib/slack/web/faraday/request.rb:11:in `post'
       12: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/slack-ruby-client-0.16.0/lib/slack/web/faraday/request.rb:26:in `request'
       11: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:279:in `post'
       10: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
        9: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
        8: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/request/multipart.rb:30:in `call'
        7: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/request/url_encoded.rb:25:in `call'
        6: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
        5: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/slack-ruby-client-0.16.0/lib/slack/web/faraday/response/raise_error.rb:25:in `call'
        4: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
        3: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/response.rb:59:in `on_complete'
        2: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:19:in `block in call'
        1: from /opt/homebrew/lib/ruby/gems/2.7.0/gems/slack-ruby-client-0.16.0/lib/slack/web/faraday/response/raise_error.rb:21:in `on_complete'
Slack::Web::Api::Errors::MethodDeprecated (method_deprecated)
```

**Comment by dblock** [comment]
@rgaufman you can help, too! I'd begin by removing those from README. The code change needs to happen in https://github.com/slack-ruby/slack-api-ref where these methods are excluded.

**Comment by dannykansas** [comment]
I'm also hitting this as a new user of the library. Happy to help with a PR, but also wondering:

Is there an existing method that can be used to lookup a channel name by it's hash ID (e.g. an alternative to the `client.channels_info(channel: 'DBXYZ4HRKL')` lookup pattern)?

**Comment by dblock** [comment]
I PRed https://github.com/slack-ruby/slack-ruby-client/pull/370 that should take care of it, appreciate a code review/someone try it out.

**Comment by dblock** [comment]
> Is there an existing method that can be used to lookup a channel name by it's hash ID (e.g. an alternative to the `client.channels_info(channel: 'DBXYZ4HRKL')` lookup pattern)?

`conversations_info` is a direct replacement and it will resolve channel IDs via https://github.com/slack-ruby/slack-ruby-client/blob/f2f2b457145fc199a111a69dcd28a4a392e50108/lib/slack/web/api/mixins/conversations.id.rb#L15
